Update jekyll.yml
Fixing running error: 
Fetching gem metadata from https://rubygems.org/...........
sass-embedded-1.77.5-x86_64-linux-gnu requires ruby version >= 3.2, which is
incompatible with the current version, 3.1.4
Error: The process '/opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle' failed with exit code 5